titles:
  - Frontend Developer
  - Junior Frontend Developer
  - Full Stack Developer
  - Junior Full Stack Developer
  - React Developer
  - JavaScript Developer
  - TypeScript Developer
  - Web Developer
  - Software Engineer
  - Technical Sourcer
  - Technical Recruiter
  - Talent Acquisition Specialist

locations:
  - Berlin
  - Germany
  - Remote Germany
  - Remote Europe
